name: Arabian Sea
description: Arabian sea is on the banks of India, Pakistan, Iran and Arabian Peninsula
twitter_usename: Arabian Sea
github_username: TheArabianSea
Author: Habibi@gmail.com

markdown: kramdown

remote_theme: just-the-docs/just-the-docs
